(* generated by dune *)

(** @canonical OpenQASM.AST *)
module AST = OpenQASM__AST

(** @canonical OpenQASM.Lexer *)
module Lexer = OpenQASM__Lexer

(** @canonical OpenQASM.Parser *)
module Parser = OpenQASM__Parser
