(* generated by dune *)

(** @canonical Voqc.BinInt *)
module BinInt = Voqc__BinInt

(** @canonical Voqc.BinNums *)
module BinNums = Voqc__BinNums

(** @canonical Voqc.BinPos *)
module BinPos = Voqc__BinPos

(** @canonical Voqc.BinPosDef *)
module BinPosDef = Voqc__BinPosDef

(** @canonical Voqc.CXCancellation *)
module CXCancellation = Voqc__CXCancellation

(** @canonical Voqc.ChangeRotationBasis *)
module ChangeRotationBasis = Voqc__ChangeRotationBasis

(** @canonical Voqc.ConnectivityGraph *)
module ConnectivityGraph = Voqc__ConnectivityGraph

(** @canonical Voqc.Datatypes *)
module Datatypes = Voqc__Datatypes

(** @canonical Voqc.FMapAVL *)
module FMapAVL = Voqc__FMapAVL

(** @canonical Voqc.FSetAVL *)
module FSetAVL = Voqc__FSetAVL

(** @canonical Voqc.FullGateSet *)
module FullGateSet = Voqc__FullGateSet

(** @canonical Voqc.GateCancellation *)
module GateCancellation = Voqc__GateCancellation

(** @canonical Voqc.GreedyLayout *)
module GreedyLayout = Voqc__GreedyLayout

(** @canonical Voqc.HadamardReduction *)
module HadamardReduction = Voqc__HadamardReduction

(** @canonical Voqc.IBMGateSet *)
module IBMGateSet = Voqc__IBMGateSet

(** @canonical Voqc.Layouts *)
module Layouts = Voqc__Layouts

(** @canonical Voqc.Main *)
module Main = Voqc__Main

(** @canonical Voqc.MappingGateSet *)
module MappingGateSet = Voqc__MappingGateSet

(** @canonical Voqc.MappingValidation *)
module MappingValidation = Voqc__MappingValidation

(** @canonical Voqc.NotPropagation *)
module NotPropagation = Voqc__NotPropagation

(** @canonical Voqc.Optimize1qGates *)
module Optimize1qGates = Voqc__Optimize1qGates

(** @canonical Voqc.OrderedTypeEx *)
module OrderedTypeEx = Voqc__OrderedTypeEx

(** @canonical Voqc.PeanoNat *)
module PeanoNat = Voqc__PeanoNat

(** @canonical Voqc.Qasm *)
module Qasm = Voqc__Qasm

(** @canonical Voqc.RotationMerging *)
module RotationMerging = Voqc__RotationMerging

(** @canonical Voqc.RzQGateSet *)
module RzQGateSet = Voqc__RzQGateSet

(** @canonical Voqc.SwapRoute *)
module SwapRoute = Voqc__SwapRoute

(** @canonical Voqc.UnitaryListRepresentation *)
module UnitaryListRepresentation = Voqc__UnitaryListRepresentation
